### ISSUE TITLE
Viz1 UX fixes

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#100]
Breathing space in control panel: 
![image](https://user-images.githubusercontent.com/10279686/74602841-12aef980-50d3-11ea-9300-165482745240.png)

Currently, elements are too tightly placed together.

**Comment by dhruv10** [comment]
Fixed in #102

**Comment by dhruv10** [comment]
Two UX issues:

1. **Jittery animation of tower objects**
I was able to reproduce the bug only when 2 - 4 instances of web app were open in different tabs simultaneously. It depends on CPU usage probably. Needs to be rigorously tested.

2. **Delayed rendering of towers**
The API response is very slow. Changing the 10k `limit` of objects (a query parameter in API) to 1k reduced fetching time from 11s (approx) to 8s (approx) that too on average not always. Though further reducing in `limit` showed not much improvement and also we cannot guard it further otherwise incomplete/ wrong information would be perceived by the FOAMViz users.
Here's the API for testing [bbox-details-nyc](https://map-api-direct.foam.space/poi/filtered?swLng=-74.14645499663825&swLat=40.63061610462643&neLng=-73.85354500336074&neLat=40.82443249938069&limit=1000&offset=0)

**Comment by dhruv10** [comment]
> Delayed rendering of towers cause of slow API response

Here are screenshots from both Postman and Insomnia:
Check the API response time
The exact endpoint is [this](https://map-api-direct.foam.space/poi/filtered?swLng=-74.14645499663825&swLat=40.63061610462643&neLng=-73.85354500336074&neLat=40.82443249938069&limit=1000&offset=0)

![image](https://user-images.githubusercontent.com/32517802/76517146-c3b27500-6482-11ea-80af-b26d22566787.png)

![image](https://user-images.githubusercontent.com/32517802/76517165-d331be00-6482-11ea-9480-d070e6b25e75.png)

**Comment by prastut** [comment]
- [x] No loading shown while fetching points from FOAM. When viz shows Delhi's map -> there is a slight delay to fetch points and then render towers on the screen. That delay from a UX perspective was earlier signified by a loader. 

- [x] Tooltip formatting issue: 
![image](https://user-images.githubusercontent.com/10279686/76826774-52d4d980-6843-11ea-946c-9857e49d48dd.png) $11 should come on the same line.

**Comment by dhruv10** [comment]
> No loading shown while fetching points from FOAM. When viz shows Delhi's map -> there is a slight delay to fetch points and then render towers on the screen. That delay from a UX perspective was earlier signified by a loader.

True, this is needed as fetching takes a very significant time now

**Comment by dhruv10** [comment]
#106
